### ISSUE TITLE
Unable to update settings

### ISSUE THREAD

**Issue by shana0780** [PrestaShop/ps_emailalerts#41] opened 2020-01-25 19:42 UTC
Hello,
I have installed the version of Mailalert for PS 1.7. (I have the version 1.7.6.2.).
When I modify a product, I have the message "Unable to update settings".

![image](https://user-images.githubusercontent.com/59194234/73126473-27f0a680-3fb3-11ea-9bf2-79a05bd7961a.png)

**Comment by shana0780** [comment] 2020-01-25 19:56
and when I try to modify the module I have the following message

Warning à la ligne 205 du fichier /home/lovingsc/www/modules/ps_emailalerts/ps_emailalerts.php
[2] count(): Parameter must be an array or an object that implements Countable

**Comment by shana0780** [comment] 2020-01-25 20:12
I find the solution.
I have changed the line 205 of ps_emailalerts.php by this one

} elseif (!empty($email) && is_array($email) && count($email) > 0) {

and now it works

**Comment by khouloudbelguith** [comment] 2020-01-27 14:45
Duplicate of https://github.com/PrestaShop/ps_emailalerts/issues/16
Fixed by https://github.com/PrestaShop/ps_emailalerts/pull/18

**Closed by khouloudbelguith** 2020-01-27 14:45 UTC
