### ISSUE TITLE
The form is always shown or never depends on the combination with which you enter.

### ISSUE THREAD

**Issue by jeroapm** [PrestaShop/ps_emailalerts#5] opened 2017-12-13 16:45 UTC
**In the frontend:**
If you open the product with a combination that is not available. The message submission form is always displayed.

If you open the product with a combination that is available. The form never comes out.

Thanks and regards

**Comment by jeroapm** [comment] 2018-01-16 09:24
There is no solution to the problem?

**Comment by LedCloud** [comment] 2018-09-02 07:13
Confirm this. version of module - 2.1.0

If the default combination is out of stock, then there is no ability to choose other combination.

If the default combination is in stock then one can change the combination. And everything works fine.

>There is no solution to the problem?
ProductSettings->Display unavailable product attributes on the product page -> No

The buyer won't be available to subscribe for the mail alert but at least the product will be available for the order.

**Comment by LedCloud** [comment] 2018-09-02 10:02
I have found the solution. 
ps_emailalerts/views/templates/hook/product.tpl

remove <form> and </form> tags.

I'll do the PR later.

**Comment by khouloudbelguith** [comment] 2018-09-03 11:07
Hi @jeroapm,

Your ticket is a duplicate of #10248
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment] 2018-09-03 11:07
Duplicate of #10248

**Closed by khouloudbelguith** 2018-09-03 11:07 UTC
