### ISSUE TITLE
 New order template with multiple customizations on same product

### ISSUE THREAD

**Issue by Lallement-Kevin** [PrestaShop/ps_emailalerts#42] opened 2020-01-28 15:12 UTC
The email sent to the vendor through "New Order" Template when a customer is ordering the same product with customization is showing all customization on each line instead of 1 by line.

Email to vendor : 
<img width="570" alt="vendor" src="https://user-images.githubusercontent.com/7900283/73276280-b9952980-41e8-11ea-97af-774fa56c35f5.png">

Email to customer is ok :
<img width="563" alt="customer" src="https://user-images.githubusercontent.com/7900283/73276277-b8fc9300-41e8-11ea-8a6b-c4910189ddc2.png">

**Comment by khouloudbelguith** [comment] 2020-01-28 15:14
Hi @Lallement-Kevin,

Here's the PR: https://github.com/PrestaShop/ps_emailalerts/pull/28 to fix the issue.
https://github.com/PrestaShop/PrestaShop/issues/16551
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2020-01-28 15:14
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16551

**Closed by khouloudbelguith** 2020-01-28 15:14 UTC
