### ISSUE TITLE
1.7.3.3 error on domain.com/module/ps_wirepayment/validation

### ISSUE THREAD

**Issue by Lanowaola** [PrestaShop/ps_emailalerts#73] opened 2020-12-10 10:12 UTC
UndefinedMethodException in ps_emailalerts.php line 552: Attempted to call an undefined method named "getLocale" of class "Language".
Did you mean to call "getLocaleByIso"?

**Comment by PierreRambaud** [comment] 2020-12-11 13:28
Hi,

We need more information to understand what's happened. You're title talk about ps_wirepayment and you're talking about ps_emailalerts.
Without more information we can do nothing for you.
Kinds regards

**Comment by Lanowaola** [comment] 2020-12-15 10:43
Hello, sorry for not explaining the problem exactly.
When the customer has placed an order and goes to the summary, this error is displayed.
When i disable ps_emailalerts everything is good.
The problem is with the sending of e-mails.

Best regards.

**Comment by MihalacheC** [comment] 2021-03-22 14:12
Hello.
I have the same issue and the same message 
" Whoops, looks like something went wrong.
1/1
UndefinedMethodException in ps_emailalerts.php line 552:
Attempted to call an undefined method named "getLocale" of class "Language".
Did you mean to call "getLocaleByIso"?
in /home/tribekar/public_html/modules/ps_emailalerts/ps_emailalerts.php line 552"
![image](https://user-images.githubusercontent.com/81167136/112002711-dbf2b080-8b28-11eb-8cab-d7b550ecb85a.png)

I guess that the issue is comming from the language, translation. Maybe something is connected to this as I "play" with those options ...
I also install a new Cash on delivery module, available and I have the same behavior.
The order is not finalized.

I REALLY appreciate any help.

**Comment by matks** [comment] 2021-03-23 17:27
Duplicate of https://github.com/PrestaShop/ps_emailalerts/issues/80

**Closed by matks** 2021-03-23 17:27 UTC
