### ISSUE TITLE
total_tax_paid is wrong with discount

### ISSUE THREAD

**Issue by neoteknic** [PrestaShop/ps_emailalerts#8] opened 2018-05-02 12:29 UTC
Total tax paid is wrong with a discount.
It show tax without discount.
ps_emailalert.php line 407

**Comment by Hlavtox** [comment] 2019-11-28 21:43
@neoteknic Made a PR with a fix: https://github.com/PrestaShop/ps_emailalerts/pull/29

**Comment by khouloudbelguith** [comment] 2019-11-29 09:09
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16227

**Closed by khouloudbelguith** 2019-11-29 09:09 UTC
